logging:
  level: debug
executor:
  queueCapacity: 200
submission:
  update:
    interval: 1000
runtime:
  timeOutSec: 3600
swagger:
  enable: true
  title: Arachne Execution Engine
  description: Arachne Execution Engine API
  version: 1.0.0
  basePackage: com.odysseusinc.arachne.executionengine.controller

kerberos:
#  kinitPath: C:\Program Files\MIT\Kerberos\bin\
#  configPath: D:\projects\Odysseus\community\ArachneExecutionEngine\src\main\docker\krb5.conf
